version: '3'
services:
  redis:
    hostname: redis
    image: redis:latest
    command: ["redis-server", "--appendonly", "no"]
    hostname: redis
    volumes:
      - ${PWD-.}/redis:/data
    restart: always
    ports:
      - "6379:6379"
  nwn-logic:
    hostname: nwnxee-server
    image: nwnxee/unified:latest
    env_file: ${PWD-.}/config/nwserver.env
    volumes:
      - ${PWD-.}/logs:/nwn/run/logs.0
      - ${PWD-.}/server/:/nwn/home
      - ${PWD-.}/logs:/nwn/data/bin/linux-x86/logs.0
    restart: always
    ports:
      - "5121:5121/udp"
  nwn-order:
    hostname: nwn-order
    image: urothis/nwn-order:latest
    env_file: ${PWD-.}/config/nwnorder.env
    restart: always
    ports:
      - "5750:5750/tcp"