version: '3'
services:
  redis:
    hostname: redis
    image: healthcheck/redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ${PWD-.}/redis:/data
    restart: unless-stopped
  caddy:
    hostname: caddy
    image: abiosoft/caddy:latest
    ports:
        -   8080:8080
    command: -root ./nwsync -port 8080 gzip
    restart: unless-stopped
  nwnxee-server:
    hostname: nwnxee
    image: nwnxee/unified:dev-nwsync
    env_file: ${PWD-.}/config/nwserver.env
    stdin_open: true
    tty: true
    links:
      - "db:db"
      - "redis:redis"
    depends_on:
      - db
      - redis
    volumes:
      - ${PWD-.}/logs:/nwn/run/logs.0
      - ${PWD-.}/server/:/nwn/home
    ports:
      - "5121:5121/udp"
    restart: always